//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cafedatabase.asp.net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class available_assortiments
    {
        public int id { get; set; }
        public Nullable<int> id_assortiment { get; set; }
        public Nullable<int> id_cafe { get; set; }
        public int quantity { get; set; }
    
        public virtual assortiments assortiments { get; set; }
        public virtual cafes cafes { get; set; }
    }
}
