//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cafedatabase.asp.net.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cafedatabaseEntities : DbContext
    {
        public cafedatabaseEntities()
            : base("name=cafedatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<assortiments> assortiments { get; set; }
        public virtual DbSet<available_assortiments> available_assortiments { get; set; }
        public virtual DbSet<cafes> cafes { get; set; }
        public virtual DbSet<cevents> cevents { get; set; }
        public virtual DbSet<comments> comments { get; set; }
        public virtual DbSet<posts> posts { get; set; }
    }
}
