//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cafedatabase.asp.net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cevents
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> scheduled_on { get; set; }
    }
}
